# Generated by Django 5.2.8 on 2025-11-08 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('six_degrees', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maker',
            old_name='culture',
            new_name='culturegroup',
        ),
        migrations.RenameField(
            model_name='maker',
            old_name='name',
            new_name='displayname',
        ),
        migrations.RenameField(
            model_name='maker',
            old_name='gender',
            new_name='makertype',
        ),
        migrations.RemoveField(
            model_name='maker',
            name='birth_year',
        ),
        migrations.RemoveField(
            model_name='maker',
            name='death_year',
        ),
        migrations.AddField(
            model_name='maker',
            name='begindate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maker',
            name='biography',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maker',
            name='enddate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maker',
            name='makerid',
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='artobject',
            name='object_id',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
