# Generated by Django 5.2.8 on 2025-11-08 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('six_degrees', '0002_rename_culture_maker_culturegroup_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artobject',
            name='maker',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Maker',
        ),
    ]
